#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR/../js/packages/web

REACT_APP_STORE_OWNER_ADDRESS_ADDRESS=A15Y2eoMNGeX4516TYTaaMErwabCrf9AB9mrzFohdQJz \
REACT_APP_STORE_ADDRESS=7jBKuCC1i113dbWmncVP8L5pV7FbS8sVmFYdGoptxAGa               \
yarn start
